version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB:       "praktikum"
      POSTGRES_USER:     "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d praktikum"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s